### PR TITLE
Notice: iconv_strpos(): Detected an illegal character in input string

### PR DESCRIPTION
**Pull request by wucdbm**
This is breaking, PHP needs to be bumped to >= 8.0

### CODE REVIEW

**Comment by wucdbm** [comment]
So the story goes like this, was wondering why things aren't being cached, turns out the cache had failed silently.
The PR title is the error checking if the string starts with this string using mb_strpos

Additionally, the conditional checker was wonky, mb_strlen always seemed to return 0, so it's now just \strlen

**Comment by b1rdex** [comment]
Can you please provide a regression test case?

AFAIK, mb_* with US-ASCII encoding were used because str_* functions may be replaced with corresponding functions from mbstring in runtime (https://www.php.net/manual/en/mbstring.configuration.php#ini.mbstring.func-overload).

I see the feature is removed in PHP 8, so I assume we're safe to get rid of mbstring.

**Comment by wucdbm** [comment]
Will do. Actually, we'll need to upgrade phpunit as well.
By the way, what's up with the weird test namespace `namespace Sp\Tests\PredisCompress`

**Comment by b1rdex** [comment]
Wow, nice finding. It should be fixed too 😬

**Comment by wucdbm** [comment]
Another update: So I just had to install `ext-mbstring` on the system due to PHPUnit 9.5, and this magically started working and it (as in the old code) keeps working even after I removed mbstring and the system library it installed.

Anyhow, I think we should take this path instead and ensure it's stable, because when it fails, it does so silently. I'll create a test for the GzipCompressor, but we should ensure it runs in an environment that does not have `ext-mbstring`, which we can't do because PHPUnit requires that.

Hmpf?

**Comment by b1rdex** [comment]
Ok, I see the issue. From the original title `Notice: iconv_strpos(): Detected an illegal character in input string` it looks like you have something in your env that replaces `mb_strpos` with `iconv_strpos`.

If I get you right, installing mbstring fixes the issue. That's fine for me.

I'm planing to release a new php 8+ version with no mbstring requirement.

**Comment by b1rdex** [comment]
~Well, actually, I'll release PHP 7.2+ version because mbstring.func_overload was removed in that version.~
Incorrect. It was deprecated in 7.2 and removed in 8.0.

**Comment by b1rdex** [comment]
Please try the new PR: https://github.com/b1rdex/predis-compressible/pull/6

**Pull request closed without merging**
